# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'predict.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PredButton = QtWidgets.QPushButton(self.centralwidget)
        self.PredButton.setGeometry(QtCore.QRect(110, 320, 93, 28))
        self.PredButton.setObjectName("PredButton")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(340, 320, 121, 28))
        self.ExitButton.setObjectName("ExitButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 561, 251))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setFontPointSize(12)
        self.PredText = QtWidgets.QLabel(self.centralwidget)
        self.PredText.setGeometry(QtCore.QRect(40, 10, 511, 41))
        self.PredText.setObjectName("PredText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ExitButton_2 = QtWidgets.QAction(MainWindow)
        self.ExitButton_2.setObjectName("ExitButton_2")
        self.menu.addAction(self.ExitButton_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Система класифікації політичної спрямованості"))
        self.PredButton.setText(_translate("MainWindow", "Розпізнати"))
        self.ExitButton.setText(_translate("MainWindow", "Вихід з програми"))
        self.PredText.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Введіть текст для розпізнавання</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "Розпізнавання"))
        self.ExitButton_2.setText(_translate("MainWindow", "Вихід з програми"))
